// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzMUvTCEcLFunaAZjz-MGzTJGS1YcNoag',
    appId: '1:543525665001:web:5cd9b251bc5e6034691878',
    messagingSenderId: '543525665001',
    projectId: 'chatapplica-e3c17',
    authDomain: 'chatapplica-e3c17.firebaseapp.com',
    storageBucket: 'chatapplica-e3c17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoX5pGnCEqLvg74GZztLQQ8faQyTf-wHA',
    appId: '1:543525665001:android:a1e722e45079a84e691878',
    messagingSenderId: '543525665001',
    projectId: 'chatapplica-e3c17',
    storageBucket: 'chatapplica-e3c17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi3eCcsK3DzNAxnJPm6LwJgmMDt5ihixI',
    appId: '1:543525665001:ios:cadc33aac1fd3615691878',
    messagingSenderId: '543525665001',
    projectId: 'chatapplica-e3c17',
    storageBucket: 'chatapplica-e3c17.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi3eCcsK3DzNAxnJPm6LwJgmMDt5ihixI',
    appId: '1:543525665001:ios:a05a82d8f4bfcd0f691878',
    messagingSenderId: '543525665001',
    projectId: 'chatapplica-e3c17',
    storageBucket: 'chatapplica-e3c17.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
